services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["node", "server.js"]

  frontend:
    build: ./client
    ports:
      - "3000:80"
